/*
 * Copyright (c) 2026 The XGo Authors (xgo.dev). All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package xai

import (
	"context"
	"errors"
	"iter"
	"strings"
)

var (
	// ErrNotFound is returned when a requested resource is not found, such as a model
	// or an action that does not exist.
	ErrNotFound = errors.New("not found")

	// ErrNotSupported is returned when a requested operation is not supported by the service.
	ErrNotSupported = errors.New("not supported")

	// ErrUnknownScheme is returned when an unknown scheme is encountered in a URL.
	ErrUnknownScheme = errors.New("unknown scheme")
)

// -----------------------------------------------------------------------------

type OptionBuilder interface {
	WithBaseURL(base string) OptionBuilder
}

// -----------------------------------------------------------------------------

type ParamBuilder interface {
	// System prompt.
	//
	// A system prompt is a way of providing context and instructions to AI, such
	// as specifying a particular goal or role.
	System(TextBuilder) ParamBuilder

	// Input messages.
	//
	// AI models are trained to operate on alternating `user` and `assistant`
	// conversational turns. When creating a new `Message`, you specify the prior
	// conversational turns with the `messages` parameter, and the model then generates
	// the next `Message` in the conversation. Consecutive `user` or `assistant` turns
	// in your request will be combined into a single turn.
	//
	// Each input message must be an object with a `role` and `content`. You can
	// specify a single `user`-role message, or you can include multiple `user` and
	// `assistant` messages.
	//
	// If the final message uses the `assistant` role, the response content will
	// continue immediately from the content in that message. This can be used to
	// constrain part of the model's response.
	//
	// Example with a single `user` message:
	//
	// ```json
	// [{ "role": "user", "content": "Hello, AI" }]
	// ```
	//
	// Example with multiple conversational turns:
	//
	// ```json
	// [
	//
	//	{ "role": "user", "content": "Hello there." },
	//	{ "role": "assistant", "content": "Hi, I'm AI. How can I help you?" },
	//	{ "role": "user", "content": "Can you explain LLMs in plain English?" }
	//
	// ]
	// ```
	//
	// Example with a partially-filled response from AI:
	//
	// ```json
	// [
	//
	//	{
	//	  "role": "user",
	//	  "content": "What's the Greek name for Sun? (A) Sol (B) Helios (C) Sun"
	//	},
	//	{ "role": "assistant", "content": "The best answer is (" }
	//
	// ]
	// ```
	//
	// Each input message `content` may be either a single `string` or an array of
	// content blocks, where each block has a specific `type`. Using a `string` for
	// `content` is shorthand for an array of one content block of type `"text"`. The
	// following input messages are equivalent:
	//
	// ```json
	// { "role": "user", "content": "Hello, AI" }
	// ```
	//
	// ```json
	// { "role": "user", "content": [{ "type": "text", "text": "Hello, AI" }] }
	// ```
	//
	// Note that if you want to include a system prompt, you can use the
	// top-level `system` parameter — there is no `"system"` role for input messages in
	// the Messages API.
	//
	// There is a limit of 100,000 messages in a single request.
	Messages(msgs ...MsgBuilder) ParamBuilder

	// Reference of tools that the model may use. The tool can be:
	// 1) User-defined tools defined with `ToolDef`.
	// 2) Std-tools, e.g. WebSearchTool, etc.
	//
	// If you include `tools` in your API request, the model may return `tool_use`
	// content blocks that represent the model's use of those tools. You can then run
	// those tools using the tool input generated by the model and then optionally
	// return results back to the model using `tool_result` content blocks.
	Tools(tools ...ToolBase) ParamBuilder

	// The model that will complete your prompt.
	Model(model Model) ParamBuilder

	// The maximum number of tokens to generate before stopping.
	//
	// Note that our models may stop _before_ reaching this maximum. This parameter
	// only specifies the absolute maximum number of tokens to generate.
	//
	// Different models have different maximum values for this parameter.
	MaxOutputTokens(int64) ParamBuilder

	// Compact when the input tokens exceed the given value. When the model triggers
	// compaction, it will return a compaction block in the response and discard part
	// of the conversation history. The content of the compaction block is an opaque
	// string that is passed back by the provider when the compaction is triggered.
	// The format of the content is provider-specific.
	Compact(maxInputTokens int64) ParamBuilder

	// Container identifier for reuse across requests.
	Container(string) ParamBuilder

	// Specifies the geographic region for inference processing. If not specified, the
	// workspace's `default_inference_geo` is used.
	InferenceGeo(string) ParamBuilder

	// Amount of randomness injected into the response.
	//
	// Defaults to `1.0`. Ranges from `0.0` to `1.0`. Use `temperature` closer to `0.0`
	// for analytical / multiple choice, and closer to `1.0` for creative and
	// generative tasks.
	//
	// Note that even with `temperature` of `0.0`, the results will not be fully
	// deterministic.
	Temperature(float64) ParamBuilder

	// Only sample from the top K options for each subsequent token.
	//
	// Used to remove "long tail" low probability responses.
	// [Learn more technical details here](https://towardsdatascience.com/how-to-sample-from-language-models-682bceb97277).
	//
	// Recommended for advanced use cases only. You usually only need to use
	// `temperature`.
	TopK(int64) ParamBuilder

	// Use nucleus sampling.
	//
	// In nucleus sampling, we compute the cumulative distribution over all the options
	// for each subsequent token in decreasing probability order and cut it off once it
	// reaches a particular probability specified by `top_p`. You should either alter
	// `temperature` or `top_p`, but not both.
	//
	// Recommended for advanced use cases only. You usually only need to use
	// `temperature`.
	TopP(float64) ParamBuilder
}

// -----------------------------------------------------------------------------

// StopReason represents the reason why the model stopped generating tokens. This
// can be used to determine whether the model stopped because it reached the end
// of the response, or because it hit a maximum token limit, or for some other reason.
type StopReason string

const (
	EndTurn                    StopReason = "end_turn"
	StopCompaction             StopReason = "compaction"
	StopMaxTokens              StopReason = "max_tokens"
	StopSequence               StopReason = "stop_sequence"
	MalformedToolUse           StopReason = "malformed_tool_use"
	PauseTurn                  StopReason = "pause_turn"
	Refusal                    StopReason = "refusal"
	Recitation                 StopReason = "recitation"
	ModelContextWindowExceeded StopReason = "model_context_window_exceeded"
	UnsupportedLanguage        StopReason = "unsupported_language"
	Unspecified                StopReason = "unspecified"
)

// Candidate represents a single candidate response from the model. A GenResponse
// may contain multiple candidates, and the model may return them in different
// orders based on the sampling parameters used in the request.
type Candidate interface {
	Parts() int
	Part(i int) Part
	StopReason() StopReason
	ToMsg() MsgBuilder
}

// GenResponse represents the response from a generation request. It contains one
// or more candidates, which are the different possible completions generated by
// the model for the given input and parameters.
type GenResponse interface {
	Len() int
	At(i int) Candidate
}

// -----------------------------------------------------------------------------

// Feature represents the capabilities of a Service. It is used to indicate which
// features are supported by a particular Service implementation, such as whether
// it supports the Gen API, GenStream API, or long-running operations.
//
// Services can support multiple features, which can be combined using bitwise OR.
// For example, a Service that supports both the Gen API and long-running operations
// would have a Feature value of `FeatureGen | FeatureOperation`.
type Feature int

const (
	FeatureGen Feature = 1 << iota
	FeatureGenStream
	FeatureOperation
)

type Service interface {
	// objectFactory creates a new instance of objects defined in the schema.
	objectFactory

	// operationService provides methods for working with long-running operations.
	operationService

	// Features returns the capabilities of this Service, which indicates which
	// features are supported by this Service implementation, such as whether it
	// supports the Gen API, GenStream API, or long-running operations.
	Features() Feature

	// Send a structured list of input messages with text and/or image content, and the
	// model will generate the next message in the conversation.
	//
	// The Gen API can be used for either single queries or stateless multi-turn
	// conversations.
	//
	// Note: If you choose to set a timeout for this request, we recommend 10 minutes.
	Gen(ctx context.Context, params ParamBuilder, opts OptionBuilder) (GenResponse, error)

	// Send a structured list of input messages with text and/or image content, and the
	// model will generate the next message in the conversation.
	//
	// The GenStream API can be used for either single queries or stateless multi-turn
	// conversations.
	//
	// Note: If you choose to set a timeout for this request, we recommend 10 minutes.
	GenStream(ctx context.Context, params ParamBuilder, opts OptionBuilder) iter.Seq2[GenResponse, error]

	// Options returns an `OptionBuilder` that can be used to set options for
	// generation requests. This includes options like the base URL for the API
	// endpoint, etc.
	Options() OptionBuilder

	// Params returns a `ParamBuilder` that can be used to build the parameters for
	// generation requests. This includes setting the system prompt, input messages,
	// tools, and generation parameters like `max_tokens`, `temperature`, etc.
	Params() ParamBuilder

	// Images returns an `ImageBuilder` that can be used to create image content.
	Images() ImageBuilder

	// Docs returns a `DocumentBuilder` that can be used to create document content.
	Docs() DocumentBuilder

	// Texts creates a text content block with the given texts. Each text will be
	// treated as a separate text item within the block. The returned `TextBuilder`
	// can be used to further customize the text content block.
	Texts(texts ...string) TextBuilder

	// UserMsg creates a message with the `user` role, which represents input from
	// a user in a conversation. The content of the message can be built using the
	// returned `MsgBuilder`.
	UserMsg() MsgBuilder

	// AssistantMsg creates a message with the `assistant` role, which represents
	// output from the AI assistant in a conversation. The content of the message
	// can be built using the returned `MsgBuilder`.
	AssistantMsg() MsgBuilder

	// WebSearchTool returns a reference to a standard web search tool that the model
	// may use to perform web searches during a conversation.
	WebSearchTool() WebSearchTool

	// ToolDef defines a tool that the model may use. The tool is identified by a unique
	// name, and has a description that explains its functionality and usage to the model.
	// The tool definition can also include additional metadata or parameters that are
	// relevant for the tool's operation. The model can then choose to use this tool in
	// its response by including a `tool_use` content block with the corresponding tool
	// name.
	ToolDef(name string) Tool

	// Tool returns a user-defined tool that the model may use, identified by its unique
	// name. This is used to refer to a tool that has been defined with `ToolDef`.
	Tool(name string) Tool
}

// -----------------------------------------------------------------------------

// NewFunc is the function type for creating a new Provider instance from a URI.
type NewFunc = func(ctx context.Context, uri string) (Service, error)

var (
	creators = map[string]NewFunc{}
)

// Register registers a NewFunc for a specific scheme. This allows different
// services to be created based on the scheme in the URI.
func Register(scheme string, creator NewFunc) {
	creators[scheme] = creator
}

// New creates a new Service instance based on the scheme in the given URI. It
// looks up the scheme in the registered creators and calls the corresponding
// NewFunc. If the scheme is not found, it returns an ErrUnknownScheme error.
func New(ctx context.Context, uri string) (Service, error) {
	scheme := schemeOf(uri)
	if creator, ok := creators[scheme]; ok {
		return creator(ctx, uri)
	}
	return nil, ErrUnknownScheme
}

func schemeOf(uri string) (scheme string) {
	pos := strings.IndexByte(uri, ':')
	if pos > 0 {
		if uri[pos] == ':' {
			return uri[:pos]
		}
	}
	return ""
}

// -----------------------------------------------------------------------------
