/*
 * Copyright (c) 2026 The XGo Authors (xgo.dev). All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package gemini

import (
	"unsafe"

	xai "github.com/goplus/xai/spec"
	"google.golang.org/genai"
)

// -----------------------------------------------------------------------------

type response struct {
	*genai.GenerateContentResponse
}

func (p response) Len() int {
	return len(p.Candidates)
}

func (p response) At(i int) xai.Candidate {
	return candidate{p.Candidates[i]}
}

// -----------------------------------------------------------------------------

type candidate struct {
	c *genai.Candidate
}

var stopReasons = map[genai.FinishReason]xai.StopReason{
	// Token generation reached a natural stopping point or a configured stop sequence.
	genai.FinishReasonStop: xai.EndTurn,
	// Token generation reached the configured maximum output tokens.
	genai.FinishReasonMaxTokens: xai.StopMaxTokens,
	// Token generation stopped because the content potentially contains safety violations.
	// NOTE: When streaming, [content][] is empty if content filters blocks the output.
	genai.FinishReasonSafety: xai.Refusal,
	// The token generation stopped because of potential recitation.
	genai.FinishReasonRecitation: xai.Recitation,
	// The token generation stopped because of using an unsupported language.
	genai.FinishReasonLanguage: xai.UnsupportedLanguage,
	// Token generation stopped because the content contains forbidden terms.
	genai.FinishReasonBlocklist: xai.Refusal,
	// Token generation stopped for potentially containing prohibited content.
	genai.FinishReasonProhibitedContent: xai.Refusal,
	// Token generation stopped because the content potentially contains Sensitive Personally
	// Identifiable Information (SPII).
	genai.FinishReasonSPII: xai.Refusal,
	// The function call generated by the model is invalid.
	genai.FinishReasonMalformedFunctionCall: xai.MalformedToolUse,
	// Token generation stopped because generated images have safety violations.
	genai.FinishReasonImageSafety: xai.Refusal,
	// The tool call generated by the model is invalid.
	genai.FinishReasonUnexpectedToolCall: xai.MalformedToolUse,
	// Image generation stopped because the generated images have prohibited content.
	genai.FinishReasonImageProhibitedContent: xai.Refusal,
	// Image generation stopped because the generated image may be a recitation from a source.
	genai.FinishReasonImageRecitation: xai.Recitation,
}

func (p candidate) StopReason() xai.StopReason {
	if reason, ok := stopReasons[p.c.FinishReason]; ok {
		return reason
	}
	return xai.Unspecified
}

func (p candidate) Parts() int {
	return len(p.c.Content.Parts)
}

func (p candidate) Part(i int) xai.Part {
	return contentBlock{p.c.Content.Parts[i]}
}

func buildPart(part xai.Part) *genai.Part {
	return part.(contentBlock).content
}

func (p candidate) ToMsg() xai.MsgBuilder {
	var parts []*genai.Part
	if c := p.c.Content; c != nil {
		parts = c.Parts
	}
	return &msgBuilder{content: parts, role: genai.RoleModel}
}

// -----------------------------------------------------------------------------

type contentBlock struct {
	content *genai.Part
}

func (p contentBlock) AsThinking() (ret xai.Thinking, ok bool) {
	if ok = p.content.Thought; ok {
		sig := p.content.ThoughtSignature
		ret.Signature = unsafe.String(unsafe.SliceData(sig), len(sig))
		ret.Text = p.content.Text
		ret.Underlying = p.content
	}
	return
}

func (p contentBlock) AsToolUse() (ret xai.ToolUse, ok bool) {
	fn := p.content.FunctionCall
	if ok = fn != nil; ok {
		ret.ID = fn.ID
		ret.Name = fn.Name
		ret.Input = fn.Args
		ret.Underlying = fn
	}
	return
}

func (p contentBlock) AsToolResult() (ret xai.ToolResult, ok bool) {
	panic("todo")
}

func (p contentBlock) AsBlob() (ret xai.Blob, ok bool) {
	blob := p.content.InlineData
	if ok = blob != nil; ok {
		ret.DisplayName = blob.DisplayName
		ret.MIME = blob.MIMEType
		ret.BlobData = xai.BlobFromRaw(blob.Data)
	}
	return
}

func (p contentBlock) AsCompaction() (ret xai.Compaction, ok bool) {
	// gemini does not support compaction, so this always returns false.
	return
}

func (p contentBlock) Text() string {
	if p.content.Thought {
		return "" // we should not treat thought as output text
	}
	return p.content.Text
}

func (p contentBlock) Underlying() any {
	return p.content
}

// -----------------------------------------------------------------------------
