package gemini

import "github.com/goplus/xai/spec"

var restriction_editImage = map[string]*xai.Restriction{"SafetyFilterLevel": &xai.Restriction{Limit: &xai.StringEnum{Values: []string{"BLOCK_LOW_AND_ABOVE", "BLOCK_MEDIUM_AND_ABOVE", "BLOCK_NONE", "BLOCK_ONLY_HIGH"}}}, "PersonGeneration": &xai.Restriction{Limit: &xai.StringEnum{Values: []string{"ALLOW_ADULT", "ALLOW_ALL", "DONT_ALLOW"}}}, "Language": &xai.Restriction{Limit: &xai.StringEnum{Values: []string{"auto", "en", "es", "hi", "ja", "ko", "pt", "zh"}}}, "EditMode": &xai.Restriction{Limit: &xai.StringEnum{Values: []string{"EDIT_MODE_BGSWAP", "EDIT_MODE_CONTROLLED_EDITING", "EDIT_MODE_DEFAULT", "EDIT_MODE_INPAINT_INSERTION", "EDIT_MODE_INPAINT_REMOVAL", "EDIT_MODE_OUTPAINT", "EDIT_MODE_PRODUCT_IMAGE", "EDIT_MODE_STYLE"}}}}
var restriction_genImage = map[string]*xai.Restriction{"SafetyFilterLevel": &xai.Restriction{Limit: &xai.StringEnum{Values: []string{"BLOCK_LOW_AND_ABOVE", "BLOCK_MEDIUM_AND_ABOVE", "BLOCK_NONE", "BLOCK_ONLY_HIGH"}}}, "PersonGeneration": &xai.Restriction{Limit: &xai.StringEnum{Values: []string{"ALLOW_ADULT", "ALLOW_ALL", "DONT_ALLOW"}}}, "Language": &xai.Restriction{Limit: &xai.StringEnum{Values: []string{"auto", "en", "es", "hi", "ja", "ko", "pt", "zh"}}}}
var restriction_genVideo = map[string]*xai.Restriction{"CompressionQuality": &xai.Restriction{Limit: &xai.StringEnum{Values: []string{"LOSSLESS", "OPTIMIZED"}}}}
var restriction_recontextImage = map[string]*xai.Restriction{"SafetyFilterLevel": &xai.Restriction{Limit: &xai.StringEnum{Values: []string{"BLOCK_LOW_AND_ABOVE", "BLOCK_MEDIUM_AND_ABOVE", "BLOCK_NONE", "BLOCK_ONLY_HIGH"}}}, "PersonGeneration": &xai.Restriction{Limit: &xai.StringEnum{Values: []string{"ALLOW_ADULT", "ALLOW_ALL", "DONT_ALLOW"}}}}
var restriction_segmentImage = map[string]*xai.Restriction{"Mode": &xai.Restriction{Limit: &xai.StringEnum{Values: []string{"BACKGROUND", "FOREGROUND", "INTERACTIVE", "PROMPT", "SEMANTIC"}}}}
var restriction_upscaleImage = map[string]*xai.Restriction{"SafetyFilterLevel": &xai.Restriction{Limit: &xai.StringEnum{Values: []string{"BLOCK_LOW_AND_ABOVE", "BLOCK_MEDIUM_AND_ABOVE", "BLOCK_NONE", "BLOCK_ONLY_HIGH"}}}, "PersonGeneration": &xai.Restriction{Limit: &xai.StringEnum{Values: []string{"ALLOW_ADULT", "ALLOW_ALL", "DONT_ALLOW"}}}}
